apiVersion: batch/v1
kind: Job
metadata:
  name: obavi-migration
  namespace: obavi-ns
spec:
  template:
    spec:
      containers:
      - name: obavi-migration
        image: alazaref/otus-msa2024-obavi:2.1
        args: ["--run-migrations"]
        env:
          - name: Database__Host
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db-host
          - name: Database__Port
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db-port
          - name: Database__Name
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db-name
          - name: Database__Username
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: db-username
          - name: Database__Password
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: db-password
      restartPolicy: OnFailure