apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obavi-ingress
  namespace: obavi-ns
spec:
  ingressClassName: nginx
  rules:
  - host: "arch.homework"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: obavi-service
            port:
              number: 80