apiVersion: v1
kind: Service
metadata:
  name: obavi-service
  namespace: obavi-ns
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: obavi